sudo: false
language: node_js
node_js:
  - 11

script: npm run test

deploy:
  provider: s3
  skip_cleanup: true
  bucket: wesww.com
  region: us-west-1
  local-dir: $TRAVIS_BUILD_DIR/dist
  access_key_id: AKIAIPN7JMCFRXSWI22A
  secret_access_key:
    secure: grDVaEFN+4+ZFRc4HkVm7bF2PN8CsgoQeucSvtp/Jvc4Fjgwi0nvk1Gf0DYXmcoD/JRyulU/pSVN6owHz9sbSqavnexHNe+nZIqXd3aDQ0hMPrCmHoU54ANPRNZDQS6Cj03vYtKlSTO2YjPdM+Qj3cofsNQYp2kiZX2kDzpgMmrwWqK24Fp8WujG2vMh3Z6xnGYwZ/GoVoT1QEbSjPbkwWKssiubjeEN8oxbM0Et63U9bPcfyG4+Ftr8RSbDcTr63181M2mp+SNRiGrQDUryUpat0Mtxazk4OaTdYbJDioX+z7CBhiJxmm8IMm08Bfh37aUlNjpLZH83KECgIawnWxJNBy8NSUBqWLkZtSO0GtY2pYf7mwz8AHzxeXk0taVtPKpSUJeCV0WesuISy5dqEB5eNGquSnVbsoJC47LaKD+rC8X5GPpuxLkJ9bJUCNn66mLT1Cd//jETAOlErKrKZICIzxdqOdneFEvLWtwDcVaHPCfUoapA0hK7sHYm8dqguX3GPVpuRfZfsDXPeDR1pkgG3XFFja5WQEQCFBanKXZOihGkKQMtIlxQex6S0olFLm8uGIJmfUGEVaDj3RV7CXLuT9bdFpx9l0Y4875Zsl9//v/06ADk/Jt1wfZL33sjDrSlxIMqaMA/Zar4biSAnIb0SkL8t+nR/00MChvB17c=
  acl: public_read
  on:
    repo: wesww/wesww
