sudo: false
language: node_js
node_js:
  - 11

script: npm run test

deploy:
  provider: s3
  skip_cleanup: true
  bucket: wesww.com
  region: us-west-1
  local-dir: $TRAVIS_BUILD_DIR/dist
  access_key_id: AKIAIZI4CZKTMH5ENHSQ
  secret_access_key:
    secure: XU2PaMxAycAddg3q57gOb4tQ23HX9Xn0e4UTOPXI5vckQ/ZYl/KpOUgD1MvLWmpXgIMaXzJD2NTAfzpbiNX3TuyMUJN86KGaAaSgqfRvlyRr8opRFq6WsPPbeoXoAQO55NuSB7bM9EzNM2towIjRz4KvN/2Ys/xRgqJ/1lu0YuiDgCH1rtLo4KN3cbClDl0ZQuLUxY4arXv7WOA3U0idpmHobUGtwwI5lE8PEGk8x50KgtN7A9DhTiHxG44J8d2CxaTM1y3COqedzJk4JQ2KMwgYGW871H2H4skMM7vBPhKOdJgxMLDt5RDsEZUzYW4juec/tm428TnXe2OfXMz4AOaybBmQv5hBy7EVblnY/FQiuu/asgAg8XrUUzIcmYLe3jA8eZK2pWiSAP5PiBdcp+GRhw0szIEastryhLYQUYEYNYQk+A1KqA5sln31ZWokmL/3eEcSrTmabaXXautJ6FRLpHTXMyb8tjAFsWQ+rkj9CDjdwBteGkGo69h+wrecIuiIEwnBcs+HUExxhuhrVy3wM0xc/TfO+1ptvbz3HxECy1R5lX7unIjbUVkuM5Hwm1g5nBPBaGj2E3wSCp0yEEqzrd1A5Qa3kwKwxEGgSpt1Ni5555aVCHMpoOQcUS/ii41BBnW8Mhqxnlj4v0vgfDS9J2VzAhlmh3eUfPRITGU=
  acl: public_read
  on:
    repo: wesww/wesww
