sudo: false
language: node_js
node_js:
  - 11

script: npm run test

deploy:
  provider: s3
  skip_cleanup: true
  bucket: wesww.com
  region: us-west-1
  local-dir: $TRAVIS_BUILD_DIR/dist
  access_key_id: AWSAccessKeyId=AKIAIPN7JMCFRXSWI22A
  secret_access_key:
    secure: I9YpgYqGlYIeUZD1Ywx0vHH3qcQBAhWoGhYNSzmLTnw2xtCDLQDt9KlsZPvuNVeekJ+e+fNJtZuarhDJGB3vqWoIX7a3Za5zOr/Ih39LZ2Yt3JMkdwMYe8Jlsf7zw555C6yMq+VKzc5Bo0QCN1IxmdQBJ5OYKQvyX0Is8OODdRME/NSojqvepw48vAJPnYYymv+CvL5KSuxT/gS4uvGLa1HOVBQhMJe988wd3Zzt/TPYglTCjtHd+pRfgzxYwC6WL/9ZwftC/swDuk+BX5g5+oZdy73MWGpDF/6r4d5aClYTSXs7O4WsC/8+2MntqWdz2ZfypYZhE25CqQigg9GH3DtfCM15SDhyhYdgvrcTEUauV2HsFGvY+4Q6DkhSeR8JkO457JmOuDneMYRTEDxPWgWsboyq+xFgRvoPWuLjRD2poIW17xgn6HZDEFcKt9Ab+MhwRCST36v546ovgkSdwz67BEzwmCdWphv+WVm6dO4odNvaLavYY27BvstLJrjirw4N88AlHQH/D83/4MVcJSAd4sdv4KqO9iTQQilv4Fcs8exRfvZXL6dIKsKbRUa6cHk5/dLJxMJ5f5LdE91m5mVICSCeB1Ih+Dy0UtETUfAf6DWMsepQ1l6Nt7yllwb5MOh43BVYVimwaW2n+Xo8LBLh3s9Kn3i1CPUcr4+p/j8=
  acl: public_read
  on:
    repo: wesww/wesww
